### ISSUE TITLE
Fails to Load on 64Bit Install

### ISSUE THREAD

**Issue by voreisthescore** [2Retr0/PlacementPlus#1]
Mod crashes on entry due to file not found for `Assembly.load(“Stardew Valley”)`
64 Bit installs instead need to run `Assembly.load(“StardewValley”)`
This is due to different DLL names for 32bit vs 64Bit installs.
Because of this the Mod doesn’t work at all on Mac or Linux.
After cloning your repo and adjusting this locally on my machine everything worked fine.

**Comment by Sarai91** [comment]
Any plans to update this? I see you made some unreleased changes 11 days ago @2Retr0 but it looks like this particular issue is still present.

EDIT: I'm an idiot. I built your 1.2.0 version and it's working just fine on 64 bit.

**Comment by 2Retr0** [comment]
Sorry for the late response--64-bit compatibility has been added with the 1.2.0 update which I've just released! Thanks!
