### ISSUE TITLE
Cannot place under buildings that have an interaction

### ISSUE THREAD

**Issue by Sarai91** [2Retr0/PlacementPlus#2]
Trying to place a path underneath a building that has an interaction (mailbox, fish pond, hay silo, etc.) will always trigger the building instead of placing the path/floor. Placing under other buildings works fine in the new 1.2.0 version.

**Comment by 2Retr0** [comment]
I've changed the logic for placing under intractable objects/buildings with version 1.2.0: left-click will always place/swap a path/flooring (if possible) when under an interactable object; and right-click will always interact with the object.

Consequently, when placing a flooring under an interactable object/building, if left-click is held, the object/building will be interacted with as no more flooring can be placed (which is rather annoying). I plan to fix this behavior in a future update!
